services:
  db_tiweb:
    image: mysql:8.0
    container_name: tiweb_mysql_prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - tiweb_prod_mysqldata:/var/lib/mysql
      - ./database-dump:/docker-entrypoint-initdb.d:ro
    networks:
      - tiweb-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  site_tiweb:
    image: wordpress:latest
    container_name: tiweb_wp_prod
    restart: always
    depends_on:
      db_tiweb:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: db_tiweb:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - ./wp-tiweb:/var/www/html
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
    networks:
      - tiweb-network
      - webproxy

  frontend:
    build:
      context: ./frontend-angular
      dockerfile: Dockerfile.prod
    image: tiweb_web_prod:latest
    container_name: tiweb_web_prod
    restart: always
    depends_on:
      - site_tiweb
    networks:
      - tiweb-network
      - webproxy

networks:
  tiweb-network:
    driver: bridge
  webproxy:
    external: true

volumes:
  tiweb_prod_mysqldata:
